[General]
skip-proxy = 127.0.0.1, localhost, *.local, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12

[Rule]
DOMAIN-SUFFIX,githubusercontent.com,PROXY
RULE-SET,https://raw.githubusercontent.com/tauCross/cross_rules/main/block.list,REJECT
RULE-SET,https://raw.githubusercontent.com/tauCross/cross_rules/main/proxy.list,PROXY
FINAL,DIRECT